### ISSUE TITLE
Changing Max Sequence Length

### ISSUE THREAD

**Issue by tavishmcdonald** [robrua/easy-bert#1]
If I wanted to change the max sequence length, particularly to reduce from 128 to speed token embedding, how would I go about doing this? I assume I'd pull and edit bert.py to my needs. In future versions could the max sequence length be exposed to users?

**Comment by robrua** [comment]
When you initialize your easy-bert model from the one of Google's tf-hub model using the `Bert()` constructor you can pass a `max_sequence_length` argument to override the default of 128. For example, `bert = Bert("https://tfhub.dev/google/bert_multi_cased_L-12_H-768_A-12/1", max_sequence_length=32)` to set it to 32.

This setting will be preserved when saving and loading in either Python or Java.
