### ISSUE TITLE
Failed to locate the model in Java

### ISSUE THREAD

**Issue by littlesonlp** [robrua/easy-bert#11]
I tried to use it using maven and include a bert model in jar.
But it failed to find the model:
Exception in thread "main" java.lang.IllegalArgumentException: resource /com/robrua/nlp/easy-bert/bert-chinese-L-12-H-768-A-12 not found.

Can you provide a working example? Thanks.

**Comment by littlesonlp** [comment]
without /

**Comment by ayushidalmia** [comment]
Added maven dependency, yet, the following is not able to load: 

    Bert bert = Bert.load("com.robrua.nlp.easy-bert.bert-uncased-L-12-H-768-A-12");
