### ISSUE TITLE
can i use it in my java project?

### ISSUE THREAD

**Issue by SmartMapple** [robrua/easy-bert#17]
i loaded the maven project in my eclipse, and use"Bert.load()" to load the bert model, but it says"File not found"
![微信图片_20200527095449](https://user-images.githubusercontent.com/44792001/82968539-20441b80-a000-11ea-831e-35760c5ec1c8.png)

do i misunderstanding the meaning of this project? can bert run in eclipse? 
because our project're all write in java, so i wonder the answer,thanks very much.

**Comment by SmartMapple** [comment]
i use the "Pre-Generated Maven Central Models", i can get the embedding vector, but i still want to know why there is error

**Comment by ayushidalmia** [comment]
@SmartMapple  can you share what did you pass in Resource Path here :     

`Bert bert = Bert.load("Resource-Path");
`
this doesn't work for me:

`    Bert bert = Bert.load("com.robrua.nlp.easy-bert.bert-uncased-L-12-H-768-A-12");
`

**Comment by SmartMapple** [comment]
> @SmartMapple can you share what did you pass in Resource Path here :
> 
> `Bert bert = Bert.load("Resource-Path"); `
> this doesn't work for me:
> 
> ` Bert bert = Bert.load("com.robrua.nlp.easy-bert.bert-uncased-L-12-H-768-A-12");`

I used this: 
Bert bert = Bert.load("com/robrua/nlp/easy-bert/bert-uncased-L-12-H-768-A-12")

when i try this project, i also met some question, some question is about maven and its import jars.
