### ISSUE TITLE
the model file

### ISSUE THREAD

**Issue by 256785** [robrua/easy-bert#3]
Could you show me the detail of java version of model ? I download the model from Google without directory of assets

**Comment by robrua** [comment]
Hey,

The Java bindings are built for use with models saved using the Python bindings. You can instantiate a model in Python by doing
```python
from easybert import Bert
bert = Bert("https://tfhub.dev/google/bert_multi_cased_L-12_H-768_A-12/1")
```
then save it with
```python
bert.save("/path/to/your/model/")
```
and can then load the model in Java.
